spring:
  profiles:
    active: local
  application:
    name: platfra-core
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  config:
    import:
      - ./application-local-oauth.yml
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: gsmsoftcorp@gmail.com
#    password: jxxklqkabtgicflr
#mail:
#  debug: false
#  transport:
#    protocol: smtp
#  smtp:
#    auth: true
#    starttls:
#      enable: true
# 메일 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: gsm.platfra@gmail.com
    password: widynnbsksgznwjn
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

# 프리마커 템플릿 설정
  freemarker:
    template-loader-path: classpath:/templates/mail
    content-type: text/html
    charset: UTF-8

server:
  port: 8080
  servlet:
    context-path: /api
  tomcat:
    mbeanregistry:
      enabled: true
#jwt:
#  token:
#    key: raondanmi
#
#restApiKey: adc470e1945ce26d54c2c1052d0a36ba

# Custom Value
custom:
  defaultFrom: help@platfra.com