spring:
  config:
    activate:
      on-profile: local
  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        default_batch_fetch_size: 100
  datasource:
    url: jdbc:p6spy:mariadb://flatfra-dev.c1ks6uyqk5sj.ap-northeast-2.rds.amazonaws.com:3306/platfradev
    username: admin
    password: platfradev
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    com.gsm.platfra: DEBUG
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
# AWS S3 연결 정보
cloud:
  aws:
    s3:
      bucket: platfra
    stack.auto: false     # CloudFormation이 없으면 실행 안되므로 false
    region.static: ap-northeast-2       # 지역 한국 고정
    fileLocation: https://%s.s3.%s.amazonaws.com/%s

#cloud:
#  aws:
#    credentials:
#      accessKey: AKIAUWND6NY7NCZQF75P
#      secretKey: 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
#    s3:
#      bucket:
#        name: gsm-bucket-root
#        url: https://gsm-bucket-root.s3.ap-northeast-2.amazonaws.com/
#        folders:
#          master: master/
#          board: board/
#          account: account/
#          account-profile: account/profile/
#    region:
#      static: ap-northeast-2
#    stack:
#      auto: false
security:
  jwt:
    secret-key: platfralocaltestjwtsecretkeyineedlongstringformypassword12v3jr9ck2j5fbdvb2sdf24hdffg34g3g
    access-token-validity-in-milliseconds: 43200000
    refresh-token-validity-in-milliseconds: 43200000
    access-token-expired-time-ms: 43200000

